version: '3.7'

services:
  app:
    image: node:14-alpine
    command: |
      npm install
      npm run build
      npm start
    volumes:
      - ./:/app
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

volumes:
  db: